# Generated by Django 4.2.6 on 2024-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0004_alter_category_category_name_alter_category_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitem",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
