# Generated by Django 4.2.6 on 2024-01-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipe", "0006_alter_recipeitem_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipeitem",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
